#!/usr/bin/env node

const fs = require('fs');
const parse = require('csv-parse');
const data = [];

console.log(process.argv);
console.log(process.cwd());

const csvFile = 'lab/node_script/faithful.csv';

fs.createReadStream(csvFile)
  .pipe(parse())
  .on('data', row => data.push(row))
  .on('end', () => {
    let json = [];
    data.shift();
    data.forEach(d => {
      json.push({
        index: +d[0],
        eruptions_length_mins: +d[1],
        eruptions_wait_mins: +d[2]
      })
    });

    console.log(json);
    fs.writeFileSync('data.json', JSON.stringify(json), null);
  });
